### ISSUE TITLE
cdk synth --no-staging > template.yaml

### ISSUE THREAD

**Issue by cassiolpaixao90** [floydspace/aws-lambda-nodejs-esbuild#6]
Hey, when try generate result cdk synth to template.yaml occur an out stranger.

 `Fetch dependency graph from D:\workspace_aws\cdk-sample-sam\package.json
Adding explicit peers for dependency isin-validator
Package lock found - Using locked versions
Packing external modules: isin-validator@^1.1.1
Package took [5073 ms]
Prune: D:\workspace_aws\cdk-sample-sam\.build [3286 ms]
Resources:
  CompleteExampleFunctionServiceRole8C2D7CB0:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com`

**Comment by floydspace** [comment]
Hey @cassiolpaixao90 thank you for the issue. Seems like we have to avoid displaying log messages from the plugin otherwise it pollutes the output. For now you could workaround this particular case with the command: `cdk synth --no-staging | tail -n +7 > template.yaml`
