### ISSUE TITLE
postinstall script in 1.1.4 causes install issues

### ISSUE THREAD

**Issue by jagregory** [floydspace/aws-lambda-nodejs-esbuild#8]
Hey folks,

In 007b1343180e6b40471c2494a74557185d340c5d a `postinstall` script was added, and when I now install the package it tries to run `tsc` on my entire repo which I don't think is intended (and fails spectacularly 🙂). Is this script needed?

Cheers

**Comment by floydspace** [comment]
@jagregory thank you for raising the issue.
yes, indeed it's not intended. I added it in case people would like to install the package from Github repo directly, so the dist folder is generated, but didn't expect this behavior, will remove it, anyway the latest `master` is always pushed to `npm` by `semantic-release`
