### ISSUE TITLE
Can't override exclude of aws-sdk

### ISSUE THREAD

**Issue by jagregory** [floydspace/aws-lambda-nodejs-esbuild#9]
The list of excluded packages is a union of whatever the user supplies and `['aws-sdk']`, which means you can't *not exclude* aws-sdk.

```js
const exclude = union(props.exclude || [], ['aws-sdk']);
```

As [Lambda doesn't bundle the latest version of the SDK](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) this can be a problem if you depend on a newer SDK version. Ideally in this scenario I'd just bundle aws-sdk until the Lambda version is updated.

**Comment by floydspace** [comment]
@jagregory yes it does make sense as we discussed with @jogold in [this thread](https://github.com/aws/aws-cdk/pull/11289#discussion_r520121574)
I Will make the fix
Thank you for your input
